"""empty message

Revision ID: 75ee7adfbef4
Revises: b03f13c43ef3
Create Date: 2017-04-24 12:54:28.364953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75ee7adfbef4'
down_revision = 'b03f13c43ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_3', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_3', 'users', 'people', ['person'], ['id'])
    op.create_foreign_key('users_ibfk_2', 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
