"""empty message

Revision ID: 84207fe0d55e
Revises: 32c2cce0a678
Create Date: 2017-04-24 13:23:16.092575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84207fe0d55e'
down_revision = '32c2cce0a678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('people_ibfk_1', 'people', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('people_ibfk_1', 'people', 'users', ['id'], ['id'])
    # ### end Alembic commands ###
