"""empty message

Revision ID: 85a59b46c68d
Revises: 84207fe0d55e
Create Date: 2017-04-25 09:32:25.503461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85a59b46c68d'
down_revision = '84207fe0d55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_accesses')
    op.drop_table('history')
    op.drop_table('roles')
    op.drop_table('users')
    op.drop_table('preferences')
    op.drop_table('people')
    op.drop_table('annotation')
    op.drop_table('variants_db')
    op.drop_table('bam')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('query', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('long_description', mysql.TEXT(), nullable=True),
    sa.Column('db_access_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['db_access_id'], ['db_accesses.id'], name='bookmarks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('bam',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sample', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('variants_db', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variants_db'], ['variants_db.id'], name='bam_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('variants_db',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('visible_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.TEXT(), nullable=True),
    sa.Column('hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('size', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('parent_db_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('annotation',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('source', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('source_version', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('annotation', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('annotation_version', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('variants_db', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variants_db'], ['variants_db.id'], name='annotation_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('people',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lastname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('institution', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('street', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('is_laboratory', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laboratory', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('preferences',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('preferences', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='preferences_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('salt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('activation_code', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('is_password_reset', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='users_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('can_validate_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('can_delete_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('history',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_start', mysql.DATETIME(), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('query', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('long_description', mysql.TEXT(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='history_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('db_accesses',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('variants_db_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='db_accesses_ibfk_1'),
    sa.ForeignKeyConstraint(['variants_db_id'], ['variants_db.id'], name='db_accesses_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
