"""empty message

Revision ID: b03f13c43ef3
Revises: d1a72717d917
Create Date: 2017-04-24 12:01:33.626677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b03f13c43ef3'
down_revision = 'd1a72717d917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('db_accesses_ibfk_2', 'db_accesses', type_='foreignkey')
    op.drop_constraint('db_accesses_ibfk_1', 'db_accesses', type_='foreignkey')
    op.drop_column('db_accesses', 'variants_db')
    op.drop_column('db_accesses', 'user')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('db_accesses', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('db_accesses', sa.Column('variants_db', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('db_accesses_ibfk_1', 'db_accesses', 'users', ['user'], ['id'])
    op.create_foreign_key('db_accesses_ibfk_2', 'db_accesses', 'variants_db', ['variants_db'], ['id'])
    # ### end Alembic commands ###
