"""empty message

Revision ID: d1a72717d917
Revises: a5eb8f1b1dfa
Create Date: 2017-04-17 15:13:08.625346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1a72717d917'
down_revision = 'a5eb8f1b1dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('laboratory', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('person', sa.Integer(), nullable=True))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'people', ['person'], ['id'])
    op.drop_column('users', 'perple_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('perple_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'people', ['perple_id'], ['id'])
    op.drop_column('users', 'person')
    op.drop_column('people', 'laboratory')
    # ### end Alembic commands ###
